// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2nw6xPv_BG03001TjAB6E4z2OrfazSbI',
    appId: '1:218703656600:web:30cc45f91e34b5c9fa82ed',
    messagingSenderId: '218703656600',
    projectId: 'login-652dc',
    authDomain: 'login-652dc.firebaseapp.com',
    storageBucket: 'login-652dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRbQ-nkkCJ634qroIjxFTvNAHU5UQ9k74',
    appId: '1:218703656600:android:8dd589f8c20e7a14fa82ed',
    messagingSenderId: '218703656600',
    projectId: 'login-652dc',
    storageBucket: 'login-652dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0SvLpdGW1RmfKWU6DoVVa-eD9pt94MA',
    appId: '1:218703656600:ios:5e49fac83d963caafa82ed',
    messagingSenderId: '218703656600',
    projectId: 'login-652dc',
    storageBucket: 'login-652dc.appspot.com',
    iosClientId: '218703656600-0jl4vn7sfklc1sp3rkn1tmg18uqng5iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.uimg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0SvLpdGW1RmfKWU6DoVVa-eD9pt94MA',
    appId: '1:218703656600:ios:5e49fac83d963caafa82ed',
    messagingSenderId: '218703656600',
    projectId: 'login-652dc',
    storageBucket: 'login-652dc.appspot.com',
    iosClientId: '218703656600-0jl4vn7sfklc1sp3rkn1tmg18uqng5iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.uimg',
  );
}
